### ISSUE TITLE
Loading Terrain Crash When Entering Dimension

### ISSUE THREAD

**Issue by Whist34** [McJtyMods/RFTools#1424]
I run an ATM 3 v4.3 server that uses rftools-1.12-7.12, rftoolsctrl-1.12-1.6.8, and rftoolsdim-1.12-5.05.

Issue: User creates a dimension and uses the teleporter probe to teleport to his dimension.
The user then crashes with a Generating Terrain error.

Here is a link to the server log showing the error the user experienced:
[https://pastebin.com/9ca11TtW](url)

I do not have a copy of the user's log, but it does appear to be a crash at the server level. The server did not crash from this issue.

I am not sure if this is a server memory problem or if there is a bug in the mod. Please let me know if you need more details. I do not know what type of dimension he was trying to teleport to, but I can find out.

Thank you

**Comment by McJty** [comment]
The link to the pastebin is not working

**Comment by Whist34** [comment]
That is strange. I'll just paste it. It isn't long.

[04:40:26] [User Authenticator #54/INFO]: UUID of player Hexiuh is 7748ef28-8d3f-417d-ad0e-f21df48d4775
[04:40:35] [Server thread/INFO]: Hexiuh[/24.36.27.241:65474] logged in with entity id 4190013 at (-1232.0, 63.0, -486.0)
[04:40:35] [Server thread/INFO]: Hexiuh joined the game
[04:40:35] [Server thread/WARN]: Failed to handle packet for /24.36.27.241:65474
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:152) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:309) ~[amu.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1207) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1057) ~[oo.class:?]
	at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:376) ~[pl.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:165) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
	at mcjty.rftoolsdim.dimensions.world.terrain.NormalTerrainGenerator.generateHeightmap(NormalTerrainGenerator.java:136) ~[NormalTerrainGenerator.class:?]
	at mcjty.rftoolsdim.dimensions.world.terrain.NormalTerrainGenerator.generate(NormalTerrainGenerator.java:241) ~[NormalTerrainGenerator.class:?]
	at mcjty.rftoolsdim.dimensions.world.GenericChunkGenerator.func_185932_a(GenericChunkGenerator.java:318) ~[GenericChunkGenerator.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	... 15 more
[04:40:35] [Server thread/INFO]: Hexiuh lost connection: Internal server error
[04:40:35] [Server thread/INFO]: Hexiuh left the game

**Comment by Whist34** [comment]
Currently he is not able to login to the server. So I am trying to figure out how to edit his player dat file to reset him back to the overworld. Do you know how to do that?

**Comment by Whist34** [comment]
Specifically I cannot see in NBTExplorer where the rftools information is that tells the game he is in that dimension.

**Comment by McJty** [comment]
that a player is in a specific dimension is not something rftools specific. That should be a normal vanilla dimension field in level.dat somewhere

**Comment by Whist34** [comment]
I found it. It was listing him as being in dimension 3. I reset that to the overworld and set his other coordinates to be a safe spot. 

Any ideas what caused the dimension to throw those errors?
