### ISSUE TITLE
Storage Scanner voiding items on unsuccessful crafting operation

### ISSUE THREAD

**Issue by wrincewind** [McJtyMods/RFTools#1748]
Issue description:  When attempting to craft items using the Storage Scanner or a Storage Tablet linked up to the storage scanner, the Scanner will void items if it is unable to complete the craft.

Say you have 3 paper and no leather in your system and you attempt to craft a book. When you press the '1' button, the scanner will delete the 3 paper. 

Steps to reproduce: 

place a storage scanner, provide it with power, scan radius at 20. Attempt to craft an item which you have some, but not all, of the materials for. Observe the levels of those items changing.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2655
* McJtyLib: 1.12-2.6.7-SNAPSHOT
* RFTools: 1.12-7.33

Possibly incompatible mods and versions: 
Foamfixcore 7.7.4

full modlist, just to be safe: 

agricraft-2.12.0-1.12.0-a3.jar
AkashicTome-1.2-10.jar
AppleSkin-mc1.12-1.0.9.jar
AutoRegLib-1.3-16.jar
base-1.12.2-3.7.0.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
bedpatch-2.2-1.12.2.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
BetterFps-1.4.8.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
BloodMagic-1.12.2-2.2.12-97.jar
Bookshelf-1.12.2-2.3.533.jar
Botania+r1.10-354.jar
Chameleon-1.12-4.1.3.jar
Charset-Lib-0.5.0.203.jar
Charset-Tweaks-0.5.0.199.jar
Chisel-MC1.12.2-0.2.0.31.jar
chiselsandbits-14.15.jar
Clumps-3.0.0.jar
CommonCapabilities-1.12-1.4.0.jar
CTM-MC1.12-0.2.3.12.jar
CyclopsCore-1.12.2-0.11.5.jar
diethopper-1.1.jar
Ding-1.12.1-1.0.1.jar
ElevatorMod-1.12.2-1.4.0.jar
EnchantingTable-1.12-1.1.2.jar
EnderCore-1.12.2-0.5.22.jar
EnderIO-1.12.2-5.0.24.jar
extrautils2-1.12-1.7.6.jar
FactoryTech-1.12.2-1.3.8.jar
FastLeafDecay-v14.jar
foamfix-0.9.7-1.12.2-anarchy.jar
Forgelin-1.6.0.jar
FTBLib-5.0.0.13.jar
FTBUtilities-5.0.0.10.jar
gravestone-1.10.1.jar
Guide-API-1.12-2.1.5-60.jar
ImmersiveEngineering-0.12-82-core.jar
ImmersiveEngineering-0.12-82.jar
industrialcraft-2-2.8.73-ex112.jar
industrialforegoing-1.12.2-1.8.4-124.jar
infinitylib-1.12.0.jar
IntegratedDynamics-1.12.2-0.11.11.jar
IntegratedTunnels-1.12.2-1.5.5.jar
IntegrationForegoing-1.12.2-1.5.jar
inventorysorter-1.12.2-1.13.1+55.jar
ironchest-1.12.2-7.0.40.824.jar
jei_1.12.2-4.8.5.159.jar
journeymap-1.12.2-5.5.2.jar
LagGoggles-FORGE-1.12.2-4.1.jar
LLOverlayReloaded-1.1.4-mc1.12.jar
mcjtylib-1.12-2.6.7.jar
MobGrindingUtils-0.3.4.jar
modnametooltip_1.12.2-1.10.0.jar
Morph-o-Tool-1.2-16.jar
MouseTweaks-2.8-mc1.12.1.jar
MTLib-3.0.3.jar
NoNausea-MC1.12-1.0.jar
OreExcavation-1.4.113.jar
pneumaticcraft-repressurized-1.12.2-0.5.1-163.jar
PotionFingers-r1.0-2.jar
Psi-r1.1-59.jar
Quark-r1.4-123.jar
RebornCore-1.12.2-3.7.4.251-universal.jar
rftools-1.12-7.33.jar
simpleharvest-1.07.jar
StevesCarts-1.12.2-2.4.18.92.jar
StorageDrawers-1.12.2-5.3.5.jar
StorageDrawersExtras-1.12-3.1.0.jar
Tesla-1.12.2-1.0.63.jar
tesla-core-lib-1.12-1.0.13.jar
Thaumcraft-1.12.2-6.1.BETA13.jar
theoneprobe-1.12-1.4.19.jar
tinyprogressions-1.12-3.2.10 - Beta.jar
topaddons-1.12.2-1.5.0.jar
torchmaster_1.12.2-1.6.1.53.jar

**Comment by McJty** [comment]
I cannot reproduce this. What was the paper stored in? Perhaps it is a problem with that?

**Comment by wrincewind** [comment]
Both the paper and the leather are stored in an RFTools Modular Storage sitting 2 blocks away (with a Drawer Controller in between them)  
The Modular Storage has a tier 3 storage module containing 288 out of a possible 300 stacks of items. this itself is covered in a Logistics Default Storage Frame from Pneumaticcraft but I doubt that's related at all. 

This bug doesn't just affect books - I've had it eat redstone blocks and gold bars from creating Extra Utilities speed upgrades, and both of those items are stored in the Drawer system.

**Comment by McJty** [comment]
So the paper is in the modular storage then? Very weird though. I've never seen this bug reported before and I cannot reproduce it at all myself. Can you show me a screenshot of your storage scanner gui?

**Comment by wrincewind** [comment]
sure. I could probably provide you a copy of the world and modpack if you want.
https://i.imgur.com/o5XuaT3.png

**Comment by sweetsosweet** [comment]
Was about to make a new issue, but this one seems to be the same problem I just had. I'm playing FTB Continuum, and I crafted 4 gold chests to make gold storage upgrades from Storage Drawers, and they all disappeared. 

I'm sure it's partially my fault, because I added a Modular Storage system and put the blank upgrades in it, but I didn't rescan before trying to craft the recipe in the Storage Scanner so it wasn't registered (it wasn't on the list in the Storage Scanner). 

When I clicked to craft the recipe for 1 upgrade the gold chests (in my inventory) disappeared one by one, but I didn't get the gold upgrades. I searched all my inventories but couldn't find them anywhere. I ended up taking the blank upgrades out of the Modular Storage and putting them in my inventory, crafted 4 new gold chests and put them in my inventory, and I got the upgrades as expected. Nonetheless, I wouldn't expect the system to delete my items if it can't craft a recipe.

**Comment by sweetsosweet** [comment]
Hi I've attached a portion of my log so you can see the error that keeps getting spammed:

Here's a link to the full log (it's too big for pastebin): [link](https://www.dropbox.com/s/pydyvhg2qc1ayb8/latest.log?dl=0)

> [13:27:00] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.AbstractMethodError
	at mcjty.rftools.craftinggrid.TileEntityItemSource.getStackInSlot(TileEntityItemSource.java:37) ~[TileEntityItemSource.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource.access$200(TileEntityItemSource.java:16) ~[TileEntityItemSource.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource$1.next(TileEntityItemSource.java:118) ~[TileEntityItemSource$1.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource$1.next(TileEntityItemSource.java:89) ~[TileEntityItemSource$1.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.tryRecipe(StorageCraftingTools.java:58) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.testCraftItems(StorageCraftingTools.java:284) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.craft(StorageScannerTileEntity.java:182) ~[StorageScannerTileEntity.class:?]
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.craft(StorageScannerTileEntity.java:165) ~[StorageScannerTileEntity.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.craftFromGrid(StorageCraftingTools.java:322) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.CommandHandler.lambda$registerCommands$19(CommandHandler.java:150) ~[CommandHandler.class:?]
	at mcjty.rftools.CommandHandler$$Lambda$1255/1782084150.execute(Unknown Source) ~[?:?]
	at mcjty.lib.McJtyLib.handleCommand(McJtyLib.java:100) ~[McJtyLib.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler.handle(PacketSendServerCommand.java:51) ~[PacketSendServerCommand$Handler.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler.lambda$onMessage$0(PacketSendServerCommand.java:46) ~[PacketSendServerCommand$Handler.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler$$Lambda$3108/845504357.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:889]: REQUEST ATTEMPT: Iron Rod (amount -1)
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 257,88,-12 -> Air (0) todo=64
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 257,79,-6 -> Air (0) todo=64
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStackFromInv:872]:     ITEM Iron Rod (index 35)   -> extracted = Iron Rod (4)
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 257,79,-7 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 257,79,-9 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 257,79,-4 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 255,73,-8 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 262,79,-4 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 251,74,-1 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 257,71,-2 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 265,71,-2 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 264,74,-16 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 257,73,-15 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 265,73,-13 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 259,78,-6 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 260,79,-4 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 251,73,-15 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 254,76,-16 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 264,79,-4 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 265,79,-9 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 265,80,-4 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 255,74,-7 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 256,74,-8 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 255,74,-9 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 258,73,-16 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 258,73,-14 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 257,79,-10 -> Iron Rod (4) todo=60
[13:27:05] [Server thread/INFO]: [mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity:requestStack:925]: ATTEMPT(a) from 254,76,-14 -> Iron Rod (4) todo=60
[13:27:15] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.AbstractMethodError
	at mcjty.rftools.craftinggrid.TileEntityItemSource.getStackInSlot(TileEntityItemSource.java:37) ~[TileEntityItemSource.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource.access$200(TileEntityItemSource.java:16) ~[TileEntityItemSource.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource$1.next(TileEntityItemSource.java:118) ~[TileEntityItemSource$1.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource$1.next(TileEntityItemSource.java:89) ~[TileEntityItemSource$1.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.tryRecipe(StorageCraftingTools.java:58) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.testCraftItems(StorageCraftingTools.java:284) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.craft(StorageScannerTileEntity.java:182) ~[StorageScannerTileEntity.class:?]
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.craft(StorageScannerTileEntity.java:165) ~[StorageScannerTileEntity.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.craftFromGrid(StorageCraftingTools.java:322) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.CommandHandler.lambda$registerCommands$19(CommandHandler.java:150) ~[CommandHandler.class:?]
	at mcjty.rftools.CommandHandler$$Lambda$1255/1782084150.execute(Unknown Source) ~[?:?]
	at mcjty.lib.McJtyLib.handleCommand(McJtyLib.java:100) ~[McJtyLib.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler.handle(PacketSendServerCommand.java:51) ~[PacketSendServerCommand$Handler.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler.lambda$onMessage$0(PacketSendServerCommand.java:46) ~[PacketSendServerCommand$Handler.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler$$Lambda$3108/845504357.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by togreglove** [comment]
I seem to only have the problem when I include Oak Framed Chest from Bibliocraft in the list of routable inventories. I have had problems with piping to these drawers before and they may be coded incorrectly.  As an indicator of the issue, when the Oak Framed Chest was included in the list of routable inventories, hovering over the craft 1 button did *not* show any items as unavailable for the craft (red highlight), but when I removed them from the list, the red highlight returned.  Hopes this helps?

**Comment by togreglove** [comment]
Having this issue in Enigmatica 2 Expert Skyblock.  Removing the Oak Framed Chests from the routable list seems to resolve the issue. They may be coded improperly as I have had issues with them not working with pipes properly before.

**Comment by NillerMedDild** [comment]
This seems somewhat related: Manually placing items in the recipe section voids them. It seems to be any item.
Screenshot of the setup:
![billede](https://user-images.githubusercontent.com/21295394/49792267-95e7f900-fd32-11e8-9dbc-753a0d244c90.png)

**Comment by NillerMedDild** [comment]
`rftools-1.12-7.59`
I'll try to reproduce it with only RFTools and JEI.

**Comment by NillerMedDild** [comment]
My issue seems to be caused by another mod, there are plenty possible culprits, so I won't bother you with it ^^

This issue seems to be caused by wrongly implemented storage blocks, it cannot be reproduced with RFTools alone.

**Comment by ProtazLV** [comment]
Hey! I am having the same issue in Project Ozone 3

**Comment by Explodey-Wolf** [comment]
> Hey! I am having the same issue in Project Ozone 3

Are you using framed chests from bibliocraft?
