### ISSUE TITLE
Problems adding Meta Block to Dimlets.json

### ISSUE THREAD

**Issue by Grim187** [McJtyMods/RFTools#1750]
I'm trying to add silicon ore from galacticraftcore which is basic_block_core metadata 8
I've tried adding a meta category below, I've tried a .8 on the end of the name based on other entries and I have tried adding a property but it always fails on line 5 column 5.

I'm thinking the block name has to specify the meta because its failing on line 5 and not 7
![2018-05-22_17 41 08](https://user-images.githubusercontent.com/4967174/40397408-72bac614-5de7-11e8-956d-7b5da4ff4362.png)

```
 [
{
	"filter": {
      "mod": "galacticraftcore"
	  "name": "basic_block_core"
      "type": "material"
	  "property": { "type": "8" } 
    },
    "settings": {
      "rarity": 4,
      "create": 20000,
      "maintain": 6000,
      "ticks": 150,
      "worldgen": true,
      "dimlet": true
    }

```

```
 [
{
	"filter": {
      "mod": "galacticraftcore"
	  "name": "basic_block_core"
      "type": "material"
	  "meta": "8"
    },
    "settings": {
      "rarity": 4,
      "create": 20000,
      "maintain": 6000,
      "ticks": 150,
      "worldgen": true,
      "dimlet": true
    }

```
```
 [
{
	"filter": {
      "mod": "galacticraftcore"
	  "name": "basic_block_core.8"
      "type": "material" 
    },
    "settings": {
      "rarity": 4,
      "create": 20000,
      "maintain": 6000,
      "ticks": 150,
      "worldgen": true,
      "dimlet": true
    }

```

```
[Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools Dimensions (rftoolsdim)

Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 5 column 5 path $[0].filter.mod
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[Streams.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRulesFromFile(DimletRules.java:145) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRulesFromFile(DimletRules.java:134) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRules(DimletRules.java:89) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.proxy.CommonProxy.preInit(CommonProxy.java:47) ~[CommonProxy.class:?]
	at mcjty.rftoolsdim.proxy.ServerProxy.preInit(ServerProxy.java:12) ~[ServerProxy.class:?]
	at mcjty.rftoolsdim.RFToolsDim.preInit(RFToolsDim.java:91) ~[RFToolsDim.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) ~[forge-1.12.2-14.23.3.2698-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[forge-1.12.2-14.23.3.2698-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[forge-1.12.2-14.23.3.2698-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 5 column 5 path $[0].filter.mod
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[TypeAdapters$29.class:?]
	at com.google.gson.internal.Streams.parse(Streams.java:48) ~[Streams.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRulesFromFile(DimletRules.java:145) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRulesFromFile(DimletRules.java:134) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.config.DimletRules.readRules(DimletRules.java:89) ~[DimletRules.class:?]
	at mcjty.rftoolsdim.proxy.CommonProxy.preInit(CommonProxy.java:47) ~[CommonProxy.class:?]
	at mcjty.rftoolsdim.proxy.ServerProxy.preInit(ServerProxy.java:12) ~[ServerProxy.class:?]
	at mcjty.rftoolsdim.RFToolsDim.preInit(RFToolsDim.java:91) ~[RFToolsDim.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) ~[forge-1.12.2-14.23.3.2698-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[forge-1.12.2-14.23.3.2698-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[forge-1.12.2-14.23.3.2698-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_161]
[17:25:31] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Users\Grim\Desktop\Shared\Minecraft Servers\Grimmance\.\crash-reports\crash-2018-05-22_17.25.31-server.txt
[17:25:31] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[17:25:31] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds

```
Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2698
* McJtyLib: 1.12-2.6.7
* RFTools Dim: 1.12-5.53

**Comment by josephcsible** [comment]
A `JsonSyntaxException` means your file isn't even valid JSON. Try using https://jsonlint.com/ to find and fix the problem.

**Comment by Grim187** [comment]
I had it formatted wrong, completely forgot the commas at the end of each line for filter and the brackets where wrong too.

Thanks!

for future reference this worked; 

```
[{
		"filter": {
			"mod": "galacticraftcore",
			"name": "basic_block_core",
			"type": "material",
			"property": {
				"type": "8"
			}
		},
		"settings": {
			"rarity": 4,
			"create": 20000,
			"maintain": 6000,
			"ticks": 150,
			"worldgen": true,
			"dimlet": true
		}
	},
```
