### ISSUE TITLE
Server crash when crafting with Storage Scanner

### ISSUE THREAD

**Issue by JaSpr** [McJtyMods/RFTools#1761]
Issue description: 
One of our users was using a Storage Scanner. When he attempted to crash something with the scanner, it crashed the server.  Once the server was back up, he tried to access the Scanner GUI, which resulted in another crash.  To verify that he was causing it, we had him try to access the GUI one more time, and it again crashed the server.

Steps to reproduce: 
1. Setup scanner
2. Access GUi
3. Start crafting
* Causes crash
4. After restart, try to access scanner
* More crash.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* McJtyLib: 2.6.7
* RFTools: 7.33

ModPack: ATM3

Relevant logs, if any: 
```
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
        at net.minecraft.util.Util.runTask(SourceFile:537)
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.minecraft.util.Util.func_181617_a(SourceFile:537)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        ... 2 more
```

**Comment by McJty** [comment]
Did the scanner work before?
What about other scanners?

**Comment by McJty** [comment]
Also I need the full crashlog

**Comment by JaSpr** [comment]
1) the scanner worked before, i just never tried crafting on the server
2) Not sure about other scanners.  We're telling our players not to use them for crafting

**Comment by JaSpr** [comment]
[crash report](https://gist.github.com/JaSpr/8719ee3ba3221fe6e3947330f563ef74)

**Comment by McJty** [comment]
The storage scanners are used a lot on servers for crafting so they normally work. Can I ask what the item was that it was trying to craft?

**Comment by JaSpr** [comment]
That's what I just asked him.  Another user said he had previously (up until a few weeks ago?) been using the storage scanners to craft, but hadn't in a while, but it also doesn't appear that ATM3 has updated RFTools in a while, so I'm checking to see what he was trying to craft.

**Comment by JaSpr** [comment]
He was trying to craft a Structure Panel from Environmental Tech

**Comment by JaSpr** [comment]
I may have a lead on this.  Will report back

**Comment by JaSpr** [comment]
Ok, so.  I was unaware that this was installed, but apparently we have the VanillaFix mod installed on our server.  It apparently handles trying to catch certain exceptions (even caught exceptions) and the default setting for VanillaFix is to open a GUI and tell the user about it (client-mod for vanilla fix).  Well, if you run it on the server, there are no GUIs, so we have to change that setting to log the exceptions.  

That said, it is probably a caught exception with crafting in the storage scanner that caused VanillaFix to crash the server.  I've updated the VanillaFix config and am closing this ticket.
