### ISSUE TITLE
NullPointerException when putting filter into filter

### ISSUE THREAD

**Issue by mcclurej06** [McJtyMods/RFTools#596]
Accidentally tried to put a Storage Filter Module into itself and received this exception.

`
java.lang.NullPointerException: Updating screen events
    at mcjty.rftools.items.storage.StorageFilterInventory.func_70296_d(StorageFilterInventory.java:114)
    at mcjty.rftools.items.storage.StorageFilterInventory.func_70299_a(StorageFilterInventory.java:86)
    at mcjty.lib.container.GhostSlot.func_75215_d(GhostSlot.java:42)
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
    at mcjty.lib.container.GenericContainer.func_75144_a(GenericContainer.java:279)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
    at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
    at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
    at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
    at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
    at mcjty.lib.container.GenericGuiContainer.func_146286_b(GenericGuiContainer.java:92)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at mcjty.lib.container.GenericGuiContainer.func_146274_d(GenericGuiContainer.java:85)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by McJty** [comment]
What version of rftools?

**Comment by mcclurej06** [comment]
4.23

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
