### ISSUE TITLE
Can't delete dimension in 1.10.2

### ISSUE THREAD

**Issue by eractnod** [McJtyMods/RFTools#657]
Version 30Beta46 on Forge 2020.  Single player world.  Trying to delete a dimension several different ways.  Made sure all configs for delete dimension set to true.

First was command rftdim safedel 9.  Get the error An unknown error occurred while attempting to perform this command.  It seemed to work as it was no longer in the dialer, but it did not delete the folder.  When making a new dimension it would try to use the same ID, and it would be powered still and be the same dimension.  Tried to delete the folder, but it was still active.
Also noted that rftdim reclaim is not a valid command anymore.

Second method of using the editor with TNT.  First time putting both in editor got this crash.
    at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.canDeleteDimension(DimensionEditorTileEntity.java:272)
    at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.validateInjectableItemStack(DimensionEditorTileEntity.java:238)
    at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.func_73660_a(DimensionEditorTileEntity.java:88)
    at net.minecraft.world.World.func_72939_s(World.java:1802)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

Logged back in and opened up editor and it was deleting dimension.  Got to 99% and then this one.
    at net.minecraftforge.common.DimensionManager.unregisterDimension(DimensionManager.java:118)
    at mcjty.rftoolsdim.dimensions.RfToolsDimensionManager.removeDimension(RfToolsDimensionManager.java:341)
    at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.safeDeleteDimension(DimensionEditorTileEntity.java:196)
    at mcjty.rftoolsdim.blocks.editor.DimensionEditorTileEntity.func_73660_a(DimensionEditorTileEntity.java:152)
    at net.minecraft.world.World.func_72939_s(World.java:1802)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

Logged back in and got the same crash a second time.  Luckly got in a third time, and it was trying to delete the dimension again.  Stopped it before it could crash again.

**Comment by eractnod** [comment]
Missed a line of the crash reports.  The first important line.
First crash with the editor and tnt.
Ticking block entity
java.lang.NullPointerException: Ticking block entity

Second crash with the editor reaching 99%
 Ticking block entity
java.lang.IllegalArgumentException: Failed to unregister dimension for id 2; No provider registered

Made a new test world for more information.
1.  Putting TNT into editor first, then the dimension, did not have the first crash, but did get the No provider registered crash once it reached 99%.
2. No provider crash again immediately on re-entering the world.
3.  Got back in on second attempt and let the dimension delete finish.  Same no provider crash at 99%.
4.  Again two attempts to get back into world.  Removed dimension and TNT from editor.
5.  rftdim list shows RFTools: id:2, T1 (power xx) owner me
6.  rftdim safedel 2 gives error An unkown error occurred while attempting to perform this command.
7.  rftdim list no longer shows the RFTools: id:2 dimension.
8.  Logged out, deleted the rftool2 folder.  Logged back in.  did rftdim list and the RfTools: id:2 is back on the list, but folder does not get re-created and it does not show up in the dialer.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
