### ISSUE TITLE
RFTools Creating A Dimension Locks Up Server 

### ISSUE THREAD

**Issue by ghost** [McJtyMods/RFTools#697]
This issue may be similar to https://github.com/McJty/RFTools/issues/673  not sure though as it does not crash the server just freezes it when the dimension being built reaches 99% then it simply spams my console with a tonne of errors. The log ended being about 14 megabytes in size by the time i managed to bring the server down by restarting the entire server itself. 

Log Can be downloaded from here [Server Log](https://www.dropbox.com/s/5ikcq9yhsmi7fxe/RfTools_Error.txt?dl=0)

RFtools version 5.1.6
Forge version 2070

**Comment by McJty** [comment]
RFTools Dimension creation is a different mod. So the version of rftools is not relevant. I need the version of RFTools Dimensions.

However from this part of the log: java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_180496_d(World.java:525) ~[aid.class:?]
	at net.minecraft.world.World.func_175685_c(World.java:470) ~[aid.class:?]
	at net.minecraft.world.World.func_175722_b(World.java:423) ~[aid.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:368) ~[aid.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:349) ~[aid.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:408) ~[aid.class:?]
	at team.chisel.common.util.GenerationHandler.replace(GenerationHandler.java:97) ~[GenerationHandler.class:?]
	at team.chisel.common.util.GenerationHandler.onLavaLakes(GenerationHandler.java:76) ~[GenerationHandler.class:?]


It appears this is a problem with chisel. Can you report to them?

**Comment by Stuart74** [comment]
version 1.10-4.30beta.47

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
