### ISSUE TITLE
[1.10.2] Trying to copy ExtraUtils2 Survival Generator with the Builder Block crashes the game

### ISSUE THREAD

**Issue by luketurner** [McJtyMods/RFTools#897]
It appears (based on the crash report, included lower in the issue) that the Builder is trying to place the Survival Generator in an "up" orientation, which the generator doesn't like. I'm not sure whether this is an ExtraUtils2 bug or an RFTools bug, but considering that I regularly see the Builder placing blocks with different orientations, I'm guessing the issue is Builder-related.

I had the Builder set to continuously place blocks when this happened to me, so it would crash as soon as the server started. I had to use MCEdit to get back into the world.

I am running a tweaked copy of the Direwolf20 modpack version 1.1.1, with a couple extra mods and newer versions.

To duplicate the bug, you just need to set up the Builder like this (with a Space Chamber Card in the builder and a Survival Generator in the chest), and turn it on:

![2016-12-03_08 00 44](https://cloud.githubusercontent.com/assets/1566148/20860513/e273a7aa-b92e-11e6-8f9a-b1bd7f33d108.png)

Crash report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  LoadingPlugin (Quark-r1.0-60.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  ForgelinPlugin (Forgelin-1.1.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-7.jar)
  IC2core (industrialcraft-2-2.6.105-ex110.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/3/16 8:00 AM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to up on block extrautils2:Machine, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:222)
	at com.rwtema.extrautils2.machine.ItemBlockMachine.placeBlockAt(ItemBlockMachine.java:90)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.placeBlockAt(BuilderTileEntity.java:998)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.copyBlock(BuilderTileEntity.java:1585)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.handleBlock(BuilderTileEntity.java:1263)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:679)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.func_73660_a(BuilderTileEntity.java:637)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:222)
	at com.rwtema.extrautils2.machine.ItemBlockMachine.placeBlockAt(ItemBlockMachine.java:90)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.placeBlockAt(BuilderTileEntity.java:998)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.copyBlock(BuilderTileEntity.java:1585)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.handleBlock(BuilderTileEntity.java:1263)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:679)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.func_73660_a(BuilderTileEntity.java:637)

-- Block entity being ticked --
Details:
	Name: rftools_builder // mcjty.rftools.blocks.builder.BuilderTileEntity
	Block type: ID #2218 (tile.rftools.builder // mcjty.rftools.blocks.builder.BuilderBlock)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-824,4,63), Chunk: (at 8,0,15 in -52,3; contains blocks -832,0,48 to -817,255,63), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Actual block type: ID #2218 (tile.rftools.builder // mcjty.rftools.blocks.builder.BuilderBlock)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP[Redacted, l='Test', x=-821.66, y=4.00, z=61.38]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -5025963373280419212
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-864,4,13), Chunk: (at 0,0,13 in -54,0; contains blocks -864,0,0 to -849,255,15), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 162656 game time, 11298 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6912 (now: false), thunder time: 19002 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2181070224 bytes (2080 MB) / 4691853312 bytes (4474 MB) up to 4691853312 bytes (4474 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5015m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.2.2171 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2171.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.2.2171} [Minecraft Forge] (forge-1.10.2-12.18.2.2171.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2-core{rv4-alpha-7} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	OpenComputers|Core{1.6.0.4} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAAAAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAAAAAAA	actuallyadditions{1.10.2-r85} [Actually Additions] (ActuallyAdditions-1.10.2-r85.jar) 
	UCHIJAAAAAAAAA	Baubles{1.3.6} [Baubles] (Baubles-1.10.2-1.3.6.jar) 
	UCHIJAAAAAAAAA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJAAAAAAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJAAAAAAAAA	appliedenergistics2{rv4-alpha-7} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-7.jar) 
	UCHIJAAAAAAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJAAAAAAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAAAAAAA	Quark{r1.0-60} [Quark] (Quark-r1.0-60.jar) 
	UCHIJAAAAAAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAAAAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHIJAAAAAAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAAAAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAAAAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAAAAAAA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJAAAAAAAAA	BloodMagic{1.9.4-2.1.0-68} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-68.jar) 
	UCHIJAAAAAAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAAAAAAA	CodeChickenLib{2.4.3.145} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAAAAAAA	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UCHIJAAAAAAAAA	Chameleon{1.10-2.2.0} [Chameleon] (Chameleon-1.10-2.2.0.jar) 
	UCHIJAAAAAAAAA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJAAAAAAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAAAAAAA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJAAAAAAAAA	IC2{2.6.105-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.105-ex110.jar) 
	UCHIJAAAAAAAAA	CompactSolars{5.0.5.329} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.5.329-universal.jar) 
	UCHIJAAAAAAAAA	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJAAAAAAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJAAAAAAAAA	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIJAAAAAAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAAAAAAA	darkutils{1.1.6.99} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.99.jar) 
	UCHIJAAAAAAAAA	forestry{5.2.16.330} [Forestry] (forestry_1.10.2-5.2.16.330.jar) 
	UCHIJAAAAAAAAA	eleccore{1.6.345} [ElecCore] (ElecCore-1.10.2-1.6.345.jar) 
	UCHIJAAAAAAAAA	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCHIJAAAAAAAAA	OpenComputers{1.6.0.4} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.4.jar) 
	UCHIJAAAAAAAAA	deepresonance{1.3.1beta1} [DeepResonance] (deepresonance-1.11-1.3.1beta1.jar) 
	UCHIJAAAAAAAAA	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UCHIJAAAAAAAAA	StorageDrawers{1.10.2-3.5.5} [Storage Drawers] (StorageDrawers-1.10.2-3.5.5.jar) 
	UCHIJAAAAAAAAA	bitdrawers{0.35} [Drawers & Bits] (DrawersBits-1.10.2-0.35.jar) 
	UCHIJAAAAAAAAA	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCHIJAAAAAAAAA	EnderIO{1.10.2-3.0.1.138_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.138_beta.jar) 
	UCHIJAAAAAAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.1.jar) 
	UCHIJAAAAAAAAA	zerocore{1.10.2-0.0.8.1} [Zero CORE] (zerocore-1.10.2-0.0.8.1.jar) 
	UCHIJAAAAAAAAA	bigreactors{0.4.5.19} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.19.jar) 
	UCHIJAAAAAAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAAAAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAAAAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.5.jar) 
	UCHIJAAAAAAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCHIJAAAAAAAAA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJAAAAAAAAA	mantle{1.10.2-1.1.2.197} [Mantle] (Mantle-1.10.2-1.1.2.jar) 
	UCHIJAAAAAAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAAAAAAA	immersiveengineering{0.10-51} [Immersive Engineering] (ImmersiveEngineering-0.10-51.jar) 
	UCHIJAAAAAAAAA	inventorysorter{0.10.0+42} [Simple Inventory sorting] (inventorysorter-1.10-0.10.0+42.jar) 
	UCHIJAAAAAAAAA	ironbackpacks{1.10.2-2.2.19} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.19.jar) 
	UCHIJAAAAAAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAAAAAAA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJAAAAAAAAA	journeymap{1.10.2-5.3.1} [JourneyMap] (journeymap-1.10.2-5.3.1.jar) 
	UCHIJAAAAAAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAAAAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAAAAAAA	mercurius{1.0.1} [Mercurius] (Mercurius-1.10.2-1.0.2.jar) 
	UCHIJAAAAAAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAAAAAAA	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCHIJAAAAAAAAA	notenoughwands{1.4.0} [Not Enough Wands] (notenoughwands-1.10-1.4.0.jar) 
	UCHIJAAAAAAAAA	psionup{15.1} [PSIonic Upgrades] (PSIonicUpgrades-r1.15.jar) 
	UCHIJAAAAAAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAAAAAAA	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJAAAAAAAAA	refinedstorage{1.2.8} [Refined Storage] (refinedstorage-1.2.8.jar) 
	UCHIJAAAAAAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAAAAAAA	rftools{5.62beta1} [RFTools] (rftools-1.11-5.62beta1.jar) 
	UCHIJAAAAAAAAA	rftoolscontrol{1.5.2beta1} [RFTools Control] (rftoolsctrl-1.11-1.5.2beta1.jar) 
	UCHIJAAAAAAAAA	rftoolsdim{4.45beta1} [RFTools Dimensions] (rftoolsdim-1.11-4.45beta1.jar) 
	UCHIJAAAAAAAAA	shadowmc{3.5.0} [ShadowMC] (ShadowMC-1.10.2-3.6.0.jar) 
	UCHIJAAAAAAAAA	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHIJAAAAAAAAA	SleepingBag{1.3.0} [Sleeping Bag] (SleepingBag-1.10.2-1.3.0.jar) 
	UCHIJAAAAAAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJAAAAAAAAA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJAAAAAAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAAAAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAAAAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
LoadingPlugin (Quark-r1.0-60.jar)
  vazkii.quark.base.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
ForgelinPlugin (Forgelin-1.1.0.jar)
  
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  li.cil.oc.common.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
AppEngCore (appliedenergistics2-rv4-alpha-7.jar)
  appeng.coremod.asm.ASMIntegration
IC2core (industrialcraft-2-2.6.105-ex110.jar)
  
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv4-alpha-7 for Forge 12.18.2.2139
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Luke/Downloads/FTBPresentsDirewolf20110/minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP[Redacted, l='Test', x=-821.66, y=4.00, z=61.38]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by meson11** [comment]
Trying to move a sequenzer also crashes the game.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
