### ISSUE TITLE
elevator crash while using optifine (multiplayer) (modpack)

### ISSUE THREAD

**Issue by Minecraftschurli** [McJtyMods/RFTools#914]
I crash every time I use the elevator when I have Optifine installed, without Optifine it works

**Comment by McJty** [comment]
I use optifine myself in my lets play and I also have an elevator. Doesn't crash for me.

Also I need a lot more info: what version of rftools, what's the crash

**Comment by Minecraftschurli** [comment]
here is the crashreport

---- Minecraft Crash Report ----
WARNING: coremods are present:
  AppEngCore (appliedenergistics2-rv4-alpha-5.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.2.334.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
Contact their authors BEFORE contacting forge
// Sorry :(
Time: 12/7/16 8:18 PM
Description: Tesselating block model
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchFieldError: field_78286_d
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at com.amadornes.rscircuits.client.ModelWrapperCircuit.func_188616_a(ModelWrapperCircuit.java:62)
	at mcmultipart.client.multipart.ModelMultipartContainer.func_188616_a(ModelMultipartContainer.java:94)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:147)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:53)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:290)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldError: field_78286_d
	at com.amadornes.rscircuits.client.SimpleModelFontRenderer.func_78266_a(SimpleModelFontRenderer.java:110)
	at net.minecraft.client.gui.FontRenderer.func_181559_a(FontRenderer.java:298)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:567)
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:680)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:425)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:404)
	at com.amadornes.rscircuits.client.ModelWrapperInnerCircuit.processQuads(ModelWrapperInnerCircuit.java:77)
	at com.amadornes.rscircuits.client.ModelWrapperInnerCircuit.func_188616_a(ModelWrapperInnerCircuit.java:39)
	at com.amadornes.rscircuits.client.ModelWrapperCircuit.lambda$null$1(ModelWrapperCircuit.java:71)
	at com.amadornes.rscircuits.client.ModelWrapperCircuit$$Lambda$833/1007464385.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.amadornes.rscircuits.client.ModelWrapperCircuit.lambda$null$2(ModelWrapperCircuit.java:65)
	at com.amadornes.rscircuits.client.ModelWrapperCircuit$$Lambda$832/650718313.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at com.amadornes.rscircuits.client.ModelWrapperCircuit.lambda$getQuads$3(ModelWrapperCircuit.java:64)
	at com.amadornes.rscircuits.client.ModelWrapperCircuit$$Lambda$831/2013811304.call(Unknown Source)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 14 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at com.amadornes.rscircuits.client.ModelWrapperCircuit.func_188616_a(ModelWrapperCircuit.java:62)
	at mcmultipart.client.multipart.ModelMultipartContainer.func_188616_a(ModelMultipartContainer.java:94)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:147)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)
-- Block model being tesselated --
Details:
	Block: mcmultipart:multipart[ticking=true]
	Block location: World: (-289,78,146), Chunk: (at 15,4,2 in -19,9; contains blocks -304,0,144 to -289,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
-- Block being tesselated --
Details:
	Block type: ID #826 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-289,78,146), Chunk: (at 15,4,2 in -19,9; contains blocks -304,0,144 to -289,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
-- Block being tesselated --
Details:
	Block type: ID #826 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-289,78,146), Chunk: (at 15,4,2 in -19,9; contains blocks -304,0,144 to -289,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:53)
-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['KaNaDa_LP'/1663, l='MpServer', x=-292.30, y=76.65, z=157.31], EntityOtherPlayerMP['MCGumba'/1073, l='MpServer', x=-298.95, y=78.00, z=149.55]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-180,64,252), Chunk: (at 12,4,12 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 28862514 game time, 7247441 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 89 total; [EntityPlayerSP['KaNaDa_LP'/1663, l='MpServer', x=-292.30, y=76.50, z=157.31], EntityPixelmon['Pinsir'/1545, l='MpServer', x=-330.21, y=89.00, z=75.06], EntityCow['Kuh'/37, l='MpServer', x=-298.71, y=64.00, z=231.23], EntityOtherPlayerMP['MCGumba'/1073, l='MpServer', x=-298.95, y=78.00, z=149.55], EntityOtherPlayerMP['MCGumba'/1073, l='MpServer', x=-298.95, y=78.00, z=149.55], EntityPig['Schwein'/50, l='MpServer', x=-259.49, y=69.00, z=138.96], EntityPig['Schwein'/51, l='MpServer', x=-262.73, y=64.00, z=198.34], EntityCow['Kuh'/52, l='MpServer', x=-265.78, y=64.00, z=222.51], EntityPixelmon['Goldini'/1588, l='MpServer', x=-235.50, y=57.01, z=140.03], EntityPixelmon['Goldini'/1589, l='MpServer', x=-235.50, y=56.07, z=123.74], NPCTrainer['Paluten'/1078, l='MpServer', x=-373.30, y=32.00, z=127.51], EntityPig['Schwein'/1079, l='MpServer', x=-355.55, y=71.00, z=179.52], EntityCow['Kuh'/58, l='MpServer', x=-246.85, y=64.00, z=208.64], EntityPixelmon['Karpador'/1597, l='MpServer', x=-289.50, y=58.46, z=186.96], EntityPixelmon['Karpador'/1598, l='MpServer', x=-298.39, y=58.43, z=201.76], EntityPixelmon['Goldini'/1599, l='MpServer', x=-281.50, y=56.00, z=181.16], EntityCartChest['Güterwaggon'/63, l='MpServer', x=-228.50, y=20.06, z=167.50], EntityCow['Kuh'/1089, l='MpServer', x=-344.49, y=81.00, z=86.20], EntityPixelmon['Webarak'/1604, l='MpServer', x=-329.50, y=87.00, z=71.50], EntityCartChest['Güterwaggon'/68, l='MpServer', x=-222.50, y=22.06, z=134.50], EntityFancyItemFrame['Cobaltrahmen'/69, l='MpServer', x=-208.03, y=69.50, z=136.50], EntityArmorStand['Rüstungsständer'/70, l='MpServer', x=-209.50, y=68.00, z=133.50], NPCRelearner['Move Relearner'/71, l='MpServer', x=-215.50, y=64.00, z=140.50], EntityCartChest['Güterwaggon'/73, l='MpServer', x=-220.50, y=18.06, z=179.50], EntityPig['Schwein'/74, l='MpServer', x=-214.22, y=65.00, z=180.78], EntityPixelmon['Digdri'/1355, l='MpServer', x=-267.50, y=25.00, z=158.50], EntityCow['Kuh'/75, l='MpServer', x=-216.67, y=63.00, z=213.09], EntityCartChest['Güterwaggon'/1102, l='MpServer', x=-248.50, y=23.06, z=93.50], EntityCow['Kuh'/1104, l='MpServer', x=-273.04, y=67.00, z=106.69], NPCTrainer['11'/1618, l='MpServer', x=-353.17, y=62.30, z=238.52], EntityCartChest['Güterwaggon'/1106, l='MpServer', x=-221.50, y=24.06, z=108.50], EntityCartChest['Güterwaggon'/1107, l='MpServer', x=-236.50, y=19.06, z=95.50], EntityPainting['Gemälde'/85, l='MpServer', x=-204.03, y=69.50, z=138.50], EntityCartChest['Güterwaggon'/86, l='MpServer', x=-198.50, y=18.06, z=162.50], EntityCartChest['Güterwaggon'/1111, l='MpServer', x=-203.50, y=26.06, z=120.50], EntityCartChest['Güterwaggon'/87, l='MpServer', x=-198.50, y=17.06, z=205.50], EntityCartChest['Güterwaggon'/1112, l='MpServer', x=-203.50, y=26.06, z=125.50], EntityCartChest['Güterwaggon'/1113, l='MpServer', x=-218.50, y

**Comment by Minecraftschurli** [comment]
and the version is 1.1x-5.70

**Comment by McJty** [comment]
It is actually crashing in Simple Circuit Maker. Report to them I think

**Comment by Minecraftschurli** [comment]
but it only crashes when the elevator is moving

**Comment by McJty** [comment]
Even then it is not crashing in rftools

**Comment by Minecraftschurli** [comment]
ok thanks

**Comment by Minecraftschurli** [comment]
I posted it in the issuetracker from SCM and they said its not a problem with their mod

**Comment by Minecraftschurli** [comment]
they said its a "mcmp bug"

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
