### ISSUE TITLE
[CRASH] Shield blocks w/ Eu2 Builder Wand

### ISSUE THREAD

**Issue by Utildayael** [McJtyMods/RFTools#997]
Crash to desktop while placing shield blocks using Eu2 builder wand. 

http://pastebin.com/7Tq5f0e0

Not sure if RFTools or ExtraUtils 2 bug... Apologies in advance if I picked poorly. :)

**RF Tools rftools-1.10-5.62
MC 1.10.2
Forge 12.18.3.2221**

```
Description: Unexpected error

java.lang.ClassCastException: mcjty.rftools.blocks.shield.TickShieldBlockTileEntity cannot be cast to gcewing.architecture.ShapeTE
	at gcewing.architecture.ShapeBlock.getLocalBounds(ShapeBlock.java:152)
	at gcewing.architecture.ShapeBlock.func_185496_a(ShapeBlock.java:109)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443)
	at net.minecraft.block.Block.func_180646_a(Block.java:375)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433)
	at net.minecraft.world.World.func_175716_a(World.java:3160)
	at com.rwtema.extrautils2.items.ItemBuildersWand.checkAndAddBlocks(ItemBuildersWand.java:64)
	at com.rwtema.extrautils2.items.ItemSelectionWand.getPotentialBlocks(ItemSelectionWand.java:189)
	at com.rwtema.extrautils2.items.ItemSelectionWand.drawSelection(ItemSelectionWand.java:289)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_552_ItemSelectionWand_drawSelection_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1329)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by McJty** [comment]
Shield blocks? You mean template blocks? What are you doing exactly?

**Comment by Utildayael** [comment]
Apologies. Shield template blocks. 

Was building out my shield template using an extra utils builder wand to speed up placement when I crashed to desktop. 

Thanks for the quick reply

**Comment by McJty** [comment]
I *think* that's a bug in either the builders wand or else in gcewing.architecture (architecture mod)?

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
